from PyQt5 import QtCore, QtGui, QtWidgets
from utilities import DB, PySecrets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 791, 551))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 191, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(280, 20, 201, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(550, 20, 221, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.le_secret_nm = QtWidgets.QLineEdit(self.groupBox)
        self.le_secret_nm.setGeometry(QtCore.QRect(10, 50, 191, 20))
        self.le_secret_nm.setObjectName("le_secret_nm")
        self.le_secret_uname = QtWidgets.QLineEdit(self.groupBox)
        self.le_secret_uname.setGeometry(QtCore.QRect(280, 50, 201, 20))
        self.le_secret_uname.setObjectName("le_secret_uname")
        self.le_secret_pw = QtWidgets.QLineEdit(self.groupBox)
        self.le_secret_pw.setGeometry(QtCore.QRect(550, 50, 221, 20))
        self.le_secret_pw.setInputMask("")
        self.le_secret_pw.setEchoMode(QtWidgets.QLineEdit.Password)
        self.le_secret_pw.setObjectName("le_secret_pw")
        self.btn_create = QtWidgets.QPushButton(self.groupBox, clicked=lambda: create_secret())
        self.btn_create.setGeometry(QtCore.QRect(320, 100, 131, 23))
        self.btn_create.setObjectName("btn_create")
        self.lbl_create = QtWidgets.QLabel(self.groupBox)
        self.lbl_create.setGeometry(QtCore.QRect(10, 130, 771, 31))
        self.lbl_create.setText("")
        self.lbl_create.setObjectName("lbl_create")
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.cmb_Update = QtWidgets.QComboBox(self.groupBox_2)
        self.cmb_Update.setGeometry(QtCore.QRect(10, 50, 191, 22))
        self.cmb_Update.setObjectName("cmb_Update")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 191, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.le_secret_pw_up = QtWidgets.QLineEdit(self.groupBox_2)
        self.le_secret_pw_up.setGeometry(QtCore.QRect(550, 50, 221, 20))
        self.le_secret_pw_up.setInputMask("")
        self.le_secret_pw_up.setEchoMode(QtWidgets.QLineEdit.Password)
        self.le_secret_pw_up.setObjectName("le_secret_pw_up")
        self.le_secret_uname_up = QtWidgets.QLineEdit(self.groupBox_2)
        self.le_secret_uname_up.setGeometry(QtCore.QRect(280, 50, 211, 20))
        self.le_secret_uname_up.setObjectName("le_secret_uname_up")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(280, 20, 201, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(550, 20, 221, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.btn_update = QtWidgets.QPushButton(self.groupBox_2, clicked=lambda: update_secret())
        self.btn_update.setGeometry(QtCore.QRect(320, 110, 131, 23))
        self.btn_update.setObjectName("btn_update")
        self.lbl_update = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_update.setGeometry(QtCore.QRect(10, 140, 771, 21))
        self.lbl_update.setText("")
        self.lbl_update.setObjectName("lbl_update")
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.cmd_delete = QtWidgets.QComboBox(self.groupBox_3)
        self.cmd_delete.setGeometry(QtCore.QRect(280, 50, 221, 22))
        self.cmd_delete.setObjectName("cmd_delete")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(280, 20, 221, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.btn_delete = QtWidgets.QPushButton(self.groupBox_3, clicked=lambda: delete_secret())
        self.btn_delete.setGeometry(QtCore.QRect(330, 100, 131, 23))
        self.btn_delete.setObjectName("btn_delete")
        self.lbl_delete = QtWidgets.QLabel(self.groupBox_3)
        self.lbl_delete.setGeometry(QtCore.QRect(0, 140, 781, 21))
        self.lbl_delete.setText("")
        self.lbl_delete.setObjectName("lbl_delete")
        self.verticalLayout.addWidget(self.groupBox_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        def update_combos():
            self.cmb_Update.clear()
            self.cmd_delete.clear()
            db = DB()
            cmb = []
            results = db.retrieve_secret_names()
            for result in results:
                cmb.append(result.secret)
            self.cmb_Update.addItems(cmb)
            self.cmd_delete.addItems(cmb)

        def create_secret():
            self.lbl_create.setText('')
            self.lbl_update.setText('')
            self.lbl_delete.setText('')
            db = DB()
            _secret = self.le_secret_nm.text()
            result = db.secret_exists(secret=_secret)
            if not result:
                secrets = PySecrets()
                _user = secrets.make_secret(self.le_secret_uname.text())
                _pass = secrets.make_secret(self.le_secret_pw.text())
                db.create_secrets(secret=_secret, username=_user, password=_pass)
                self.lbl_create.setText("Secret Created")
                self.le_secret_nm.setText('')
                self.le_secret_uname.setText('')
                self.le_secret_pw.setText('')
                update_combos()

        def update_secret():
            self.lbl_create.setText('')
            self.lbl_update.setText('')
            self.lbl_delete.setText('')
            db = DB()
            secrets = PySecrets()
            _secret = self.cmb_Update.currentText()
            _user = secrets.make_secret(self.le_secret_uname_up.text())
            _pass = secrets.make_secret(self.le_secret_pw_up.text())
            db.update_secret(secret=_secret, username=_user, password=_pass)
            self.lbl_update.setText("Secret Updated")

        def delete_secret():
            self.lbl_create.setText('')
            self.lbl_update.setText('')
            self.lbl_delete.setText('')
            _secret = self.cmd_delete.currentText()
            db = DB()
            db.delete_secret(secret=_secret)
            self.lbl_delete.setText('Secret Deleted')
            update_combos()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.le_secret_nm, self.le_secret_uname)
        MainWindow.setTabOrder(self.le_secret_uname, self.le_secret_pw)
        MainWindow.setTabOrder(self.le_secret_pw, self.btn_create)
        MainWindow.setTabOrder(self.btn_create, self.cmb_Update)
        MainWindow.setTabOrder(self.cmb_Update, self.le_secret_uname_up)
        MainWindow.setTabOrder(self.le_secret_uname_up, self.le_secret_pw_up)
        MainWindow.setTabOrder(self.le_secret_pw_up, self.btn_update)
        MainWindow.setTabOrder(self.btn_update, self.cmd_delete)
        MainWindow.setTabOrder(self.cmd_delete, self.btn_delete)
        update_combos()



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ACG Secrets Manager"))
        self.groupBox.setTitle(_translate("MainWindow", "Create New Secret"))
        self.label.setText(_translate("MainWindow", "Secret Name"))
        self.label_2.setText(_translate("MainWindow", "User Name"))
        self.label_3.setText(_translate("MainWindow", "Password"))
        self.btn_create.setText(_translate("MainWindow", "Create Secret"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Update Secret"))
        self.label_4.setText(_translate("MainWindow", "Choose Existing Secret"))
        self.label_5.setText(_translate("MainWindow", "User Name"))
        self.label_6.setText(_translate("MainWindow", "Password"))
        self.btn_update.setText(_translate("MainWindow", "Update Secret"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Delete Secret"))
        self.label_7.setText(_translate("MainWindow", "Choose Existing Secret"))
        self.btn_delete.setText(_translate("MainWindow", "Delete Secret"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
